### PR TITLE
Fix #127 - change buffer size for int16

### LINKED ISSUE #127: Can't return Int16
I have tried to have a function with return type `'n'` (int16) and in the body of the function I have `return 42`. When I run this service, it starts all right, but then when I call the function with gdbus (for instance), the service just stop running, and gdbus warns me that the recipient disconnected without replying.

### PR DESCRIPTION
**Pull request by nschoe**
I believe this was just a type, allocating a 4-byte buffer for a 2-byte type.

### CODE REVIEW

**Comment by sidorares** [comment]
👍

**Comment by sidorares** [comment]
can you look into adding this to tests as well?

**Comment by nschoe** [comment]
I'm not sure I know how or what to do? As far as I understand---but mind you, this may be wrong^^---the tests for marshalling `int16` are already present and they pass---again, I can be wrong, I'm not used to making tests:/.

The problem did not appear in the marshalling function, as calling `marshall()` on an `int16` did return a result, the problem only arose when trying to send that `int16` on the bus, this was the bus that was rejecting it because it was not correctly formatted...

So I'm not too sure how to make tests for that, do we have tests that actually interact with the bus?

**Comment by sidorares** [comment]
hm, not sure why this test did not fail before: https://github.com/sidorares/node-dbus/blob/7efa5207af537e1108fd4f2a9311f9b246c5aa9e/test/unmarshall-basic.js#L129-L130

**Comment by nschoe** [comment]
Well, what is this test supposed to do?
Because `300` and `16300` are both valid `int16` number, so they were marshalled by the function, without raising errors.
It's just that the Buffer allocated was too big for them, so there were extra (padding) data, only this was not really padding since this data was not initialized to `0`.

So the fail only happened when the buffer was actually sent to the dbus bus. This test doesn't actually send the data to DBus, does it?

**Comment by sidorares** [comment]
incorrect size was only used on marshalling, and test does data -> buffer -> data marshall/unmarshall ( I think )

**Comment by sidorares** [comment]
```js
var marshall = require('./lib/marshall.js');
var unmarshall = require('./lib/unmarshall.js');

var b = marshall('nn', [10, 10]);
console.log(unmarshall(b, 'nn'));
```

outputs  `[ 10, 271 ]`

**Comment by nschoe** [comment]
Yes, I have made the same test, returns something random for the second. So maybe the test works because in the test, only one `int16` is marshalled / unmarshalled?

**Comment by sidorares** [comment]
simplest test I can think of:

```js
var marshall = require('./lib/marshall.js');
var unmarshall = require('./lib/unmarshall.js');

var data =  [10, 1000];
var s = 'nn';

var buf = marshall(a, data);
assert.equal(buf.toString('hex'), '0xa001e80') 
assert.deepEqual(unmarshall(buf, s), data); 
```

**Comment by nschoe** [comment]
All right, seems good to me.
Can you include it in the tests? As I said, I'm not too familiar with tests and mocha yet, so it will take me forever.
When you're done, if this seems right to you, can you merge the PR?

**Comment by sidorares** [comment]
ok, will do

**Comment by nschoe** [comment]
Cool, thanks!
I'll be sure to read the tests later so that I can understand them and add some too.

**Comment by nschoe** [comment]
@sidorares thanks for pushing the test.
Can we merge now?

**Comment by sidorares** [comment]
oops, sorry completely forgot about this. Need to check why tests fail

**Comment by nschoe** [comment]
Great, thanks :-)

**Comment by nschoe** [comment]
Ah nice!
Thanks for working on that @sidorares !

(I'm making good progress on #129 myself, this is going to be good!)

LGTM, you can merge.

**Comment by sidorares** [comment]
sorry, very busy with lots of other stuff, I promise I won't left you alone @nschoe :)

**Comment by nschoe** [comment]
It's okay @sidorares , don't worry ^^
I'm still a bit new to this, this is why, for now, I prefer to submit the PR so that you can look at them before I merge them myself and screw something.

Thanks for taking care of this :-)

**Pull request merged**
