### PR TITLE
Use Long.js for 64 bit support

### PR DESCRIPTION
**Pull request by CyDragon80**
This builds off of https://github.com/sidorares/node-dbus/pull/101 and https://github.com/sidorares/node-dbus/pull/150.
Leveraging Long.js features, it can marshal numbers up to 53 bits, strings with decimal digits representing full 64 bit values, and other Long.js compatible objects into 64bit (x/t) dbus fields. When unmarshalling 64 bit (x/t) dbus fields, by default it will still convert into a number like it did previously, however there is now a 'ReturnLongjs:true' option that will cause it to return a Long.js object instead of a number. 
I have hopefully added appropriate test cases to cover this. It adds a dependency to Long.js but hopefully remains otherwise backwards compatible. I think I got the options to pass correctly down to DBusBuffer, but someone could double check. (I also stumbled upon the option 'ayBuffer' which didn't seem to be passed down to DBusBuffer previously, unless I missed something.)

### CODE REVIEW

**Comment by CyDragon80** [comment]
Apparently Node.js 0.12 does not have Object.assign(), do I need to use an alternative or is Node.js 0.12 support still required by this project?

**Comment by CyDragon80** [comment]
Borrowed an Object.assign() replacement from https://stackoverflow.com/a/30498430.
Looks like it should work for Node.js 0.12 now.

**Comment by sidorares** [comment]
maybe use object-assign from npm instead of bundling merge function? https://github.com/sidorares/node-mysql2/pull/397/commits/7f3d84f69a175fb1e4365b77d6fb8cd69b70b913

**Comment by CyDragon80** [comment]
Ok, replaced previous polyfill with object-assign.

**Comment by sidorares** [comment]
Thanks!

**Pull request merged**
