### PR TITLE
[WIP] ESLint/Prettier

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by jrobeson** [comment]
I do have eslint and prettier setup locally, but there are a few things I wanted to discuss first.

 1. What eslint rules do you want? I'm using the eslint recommended config atm with no-console turned off. Do you want anything else?
 2. What's your stance on curly brackets in if statements? Prettier seems to make a bit of a mess of them if you don't use curlies with `if`/`else`.

I'm personally in favor of always using curlies anytime an else is involved or not a single line if statement. I also prefer to use ternary on the simple if/else cases.

**Comment by sidorares** [comment]
1) nothing else
2) I'm in favour always using curlies ( even without else ), or avoiding simple if's by other means ( ternary, shortcut assignment `const foo = expression && value` etc)

**Comment by jrobeson** [comment]
what do you want to do about all this commented out code? I understand leaving them in the examples, but not sure where else. It definitely causes some problems with eslint (not including the examples).

**Comment by sidorares** [comment]
> what do you want to do about all this commented out code?

nuke it!

**Comment by jrobeson** [comment]
i submitted the prettier changes in #172 since I'm going need to do more for eslint to get it clean and correct.

**Comment by sidorares** [comment]
Thanks! #172 merged

**Comment by jrobeson** [comment]
I'm mostly new to developing node apps and dealing  with commonjs. I didn't really get started until I used typescript and es6 modules, so I'm woefully ignorant of stuff like this.  Can you explain to me what is going on with this, why, and what it should be replaced with? ESLint sure doesn't like it.

https://github.com/sidorares/node-dbus/blob/master/lib/marshall.js#L8

**Comment by sidorares** [comment]
looking at it definitely want to rewrite, confusing even to me.

The result of require'ing marshall.js is https://github.com/sidorares/node-dbus/blob/master/lib/marshall.js#L8-L24 function

**Comment by sidorares** [comment]
probably better to make it look like this:

```js
module.exports = function marshall(signature, data, offset) {
}
```

**Comment by jrobeson** [comment]
Can you also look at this? https://github.com/sidorares/node-dbus/blob/master/test/unmarshall-basic.js#L57 and search for any usages of str30000 in the file?

**Comment by sidorares** [comment]
https://github.com/sidorares/node-dbus/blob/master/test/unmarshall-basic.js#L173 ?

**Comment by jrobeson** [comment]
yeah, should that be quoted?  there?

**Comment by sidorares** [comment]
oh. No :)

**Comment by jrobeson** [comment]
I"m gonna close this PR and submit  some of it piecemeal and then a new PR to actually enable eslint.  After examining some of these eslint issues, it's definitely gonna involve at least some refactoring.

**Pull request closed without merging**
