### PR TITLE
trim trailing spaces

### PR DESCRIPTION
**Pull request by jrobeson**
`hexy.js` seems to be bundled, so i'm leaving the spaces there.

### CODE REVIEW

**Comment by jrobeson** [comment]
why is hexy bundled anyways?

**Comment by jrobeson** [comment]
Any chance you could pull this one too?

**Comment by sidorares** [comment]
As you started doing this (thank you!) - maybe add eslint+prettier hooks? For example similar to node-mysql2 - https://github.com/sidorares/node-mysql2/blob/cad78200f67849119eeebb50a3490ebbb160b72f/package.json#L18-L27

**Comment by jrobeson** [comment]
that sounds lovely.  I'll give it a go.

**Pull request merged**
