### PR TITLE
Improve test

### PR DESCRIPTION
**Pull request by lucidguppy**
Hi @sidorares - here's the rest of the validation I was talking about.  Please review and provide feedback when you can.

I also added a test for basic launching and executing methods on a service.

Note - I removed the parse signature call you did - and replaced it with the check I wrote for signatures.

### CODE REVIEW

**Comment by sidorares** [comment]
This is great! I'd like to add some integration tests as well that are able to run without dbus daemon ( using dbus server implimentation from this library )

**Comment by sidorares** [comment]
that's actually the problem in your tests :( haven't actually looked at changes, but error log indicates that you are trying to connect to a bus and travis is not happy

**Comment by lucidguppy** [comment]
I can probably move the dbus test out of the npm test - does that make sense?

**Comment by sidorares** [comment]
ideally test/test-server.js should started mocked server, but for now you can skip it if CI=1 ( return early if `process.env.CI` )

**Comment by sidorares** [comment]
I think signature parser already handles matching open/closed '({})' so validateSignature does not add anything useful ( can we just try to parse instead? )

**Comment by lucidguppy** [comment]
I've put in the proces.env.CI tests like you talked about.  I've also shrunk the signature test as much as I could using the parseSignature function (the remaining code was needed to pass the added tests).

**Comment by lucidguppy** [comment]
Dropping the dbus server test to see if travis will pass.  If this passes - I'll add PR later for the part that fails now.

**Comment by sidorares** [comment]
lgtm!

**Comment by sidorares** [comment]
As you heavily touched type system - would you like to collaborate on "simplified type serialisation/deserealisation" as discussed in #52 ?
Basically we either need to be able to transparently convert JS objects to `a{sv}` and/or as alternative provide helper functions to build complex types:

```js
var param1 = dbus.Variant('ai', [1, 2, 3]);
var param2 = dbus.Variant('iii', 1, 2, 3);
var param3 = dbus.Hash('si', { 'test', 123 } );
var param3 = dbus.Hash('sv', { 'test', dbus.Variant('i', 123) } );
// or, with simplified auto conversion
param3 = { test: 123 }
```

I think 2 main pain points for most users are: 
  - types are difficult to construct
  - type system not documented

**Comment by lucidguppy** [comment]
If you want to break small parts of the task off - perhaps I can help.

**Pull request merged**
